@TrickVaultApi_HostAddress=https://localhost:7002
@json=application/json
@Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZTZhOTgxYy1hZThmLTQ3YTQtYTcyMy0xNTJhMTAwMmU0YzEiLCJlbWFpbCI6InVzZXIyQGxvY2FsaG9zdC5jb20iLCJqdGkiOiI4ZDM1MWE4OC01MDBhLTQwMTktODU3OS0wZGJjYTM3M2VhNzkiLCJuYW1lIjoiVXNlciwgVGVzdCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE3NjAwNjkxMjIsImlzcyI6IlRyaWNrVmF1bHRBUEkiLCJhdWQiOiJUcmlja1ZhdWx0QVBJQ2xpZW50In0.8Lfm8uJ9eGi8cZLjWCXmj1QbJ9NHLmUtEKZX1S1FOCw
@id=3

########################################################
# Auth
########################################################

POST {{TrickVaultApi_HostAddress}}/api/auth/register
Content-Type: {{json}}

{
    "email": "user@localhost.com",
    "password": "P@ssword1",
    "firstName": "Test",
    "lastName": "User"
}

###

POST {{TrickVaultApi_HostAddress}}/api/auth/register
Content-Type: {{json}}

{
    "email": "admin@localhost.com",
    "password": "P@ssword1",
    "firstName": "Mark",
    "lastName": "Harrison",
    "role": "Administrator"
}

###

POST {{TrickVaultApi_HostAddress}}/api/auth/login
Content-Type: {{json}}

{
    "email": "user@localhost.com",
    "password": "P@ssword1"
}

###

POST {{TrickVaultApi_HostAddress}}/api/auth/login
Content-Type: {{json}}

{
    "email": "admin@localhost.com",
    "password": "P@ssword1"
}

########################################################
# Tricks
########################################################

GET {{TrickVaultApi_HostAddress}}/api/tricks
Authorization: Bearer {{Token}}

###

GET {{TrickVaultApi_HostAddress}}/api/tricks/{{id}}
Authorization: Bearer {{Token}}

###

POST {{TrickVaultApi_HostAddress}}/api/tricks
Content-Type: {{json}}
Authorization: Bearer {{Token}}

{
    "Title": "Linking Rings"
}                                   

###

PUT {{TrickVaultApi_HostAddress}}/api/tricks/{{id}}
Content-Type: {{json}}
Authorization: Bearer {{Token}}

{
    "Id": 3,
    "Title": "Linking Rings",
    "Effect": "Magician shows 5 disconnected rings, then manages to magically link the rings together.",
    "Method": "Use the secret of the rings to link and unlink them.",
    "Patter": "I have two completely separate rings.  But when I do this (rub the rings together), they become linked.",
    "CategoryIds": [3, 4, 5]
}

###

DELETE {{TrickVaultApi_HostAddress}}/api/tricks/{{id}}
Authorization: Bearer {{Token}}

###

########################################################
# Categories
########################################################

GET {{TrickVaultApi_HostAddress}}/api/categories
Authorization: Bearer {{Token}}

###

GET {{TrickVaultApi_HostAddress}}/api/categories/{{id}}
Authorization: Bearer {{Token}}

###

POST {{TrickVaultApi_HostAddress}}/api/categories
Content-Type: {{json}}
Authorization: Bearer {{Token}}

{
  "Name": "Self-working card tricks"
}

###

PUT {{TrickVaultApi_HostAddress}}/api/categories/{{id}}
Content-Type: {{json}}
Authorization: Bearer {{Token}}

{
  "Id": 10,
  "Name": "Money Magic"
}

###

DELETE {{TrickVaultApi_HostAddress}}/api/categories/{{id}}
Authorization: Bearer {{Token}}

###
