@TrickVault.Api_HostAddress = https://localhost:7002
@id=3

GET {{TrickVault.Api_HostAddress}}/api/tricks

###

GET {{TrickVault.Api_HostAddress}}/api/tricks/{{id}}

###

POST {{TrickVault.Api_HostAddress}}/api/tricks
Content-Type: application/json

{
    "Id": 3,
    "Title": "Linking Rings"
}

###

PUT {{TrickVault.Api_HostAddress}}/api/tricks/{{id}}
Content-Type: application/json

{
    "Id": 3,
    "Title": "Linking Rings",
    "Effect": "Magic shows 5 disconnected rings, then manages to magically link the rings together.",
    "Method": "Use the secret of the rings to link and unlink them.",
    "Patter": "I have two completely separate rings.  But when I do this (rub the rings together), they become linked."
}

###

DELETE {{TrickVault.Api_HostAddress}}/api/tricks/{{id}}

###
